version: '3.8'

x-shared-env: &shared-env
  API_PORT: ${API_PORT}
  DB_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      <<: *shared-env
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "sh -c \"pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}\""]
      interval: 5s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:alpine
    ports:
      - "${NGINX_HOST_PORT}:${NGINX_LISTEN_PORT}"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    environment:
      NGINX_LISTEN_PORT: ${NGINX_LISTEN_PORT:-8088}
      API_PORT: ${API_PORT:-8887}
      WORKER_CONNECTIONS: 4096
      KEEPALIVE: 32
      SSL_ENABLED: "false"
    command: >
      sh -c "envsubst '$$API_PORT $$NGINX_LISTEN_PORT $$WORKER_CONNECTIONS $$KEEPALIVE'
      < /etc/nginx/nginx.conf.j2 > /etc/nginx/nginx.conf
      && nginx -g 'daemon off;'"
